"""empty message

Revision ID: 1db8ab52eea1
Revises: 38524fe1fb0b
Create Date: 2021-03-17 15:28:49.216776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db8ab52eea1'
down_revision = '38524fe1fb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post', ['slug'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'post', type_='unique')
    # ### end Alembic commands ###
