"""empty message

Revision ID: 2c2fc9e2f707
Revises: 1db8ab52eea1
Create Date: 2021-03-26 15:28:51.063947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2fc9e2f707'
down_revision = '1db8ab52eea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.String(length=50), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'hash')
    # ### end Alembic commands ###
