"""Initial migration.

Revision ID: 38524fe1fb0b
Revises: 
Create Date: 2021-03-17 15:15:28.265308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38524fe1fb0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('authore', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('slug', sa.String(length=140), nullable=True))
    op.create_unique_constraint(None, 'post', ['slug'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'slug')
    op.drop_column('post', 'created')
    op.drop_column('post', 'authore')
    # ### end Alembic commands ###
